baseURL = "http://example.org/"
languageCode = "en-us"
title = "Hydra Template"
disqusShortname = ""
googleAnalytics = ""
Paginate = 10
PaginatePath = "/"
enableRobotsTXT = true

[taxonomies]
category = "categories"

[permalinks]
posts = ":section/:year/:month/:day/:title/"

[markup.goldmark.renderer]
unsafe = true

[menu]

[[menu.main]]
identifier = "login"
name = "login"
url = "/"
weight = 110
  [menu.main.params]
  new_window = true

[[menu.main]]
identifier = "signup"
name = "Sign Up"
url = "/"
weight = 111
  [menu.main.params]
  new_window = true
  highlight = true